title: "Vulaegis Safety"
description: "Industrial safety solutions"
url: "https://VulaegisSafety.github.io"  # â† Match your repo name!
theme: jekyll-theme-primer  # GitHub's default theme
plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
